from accion_inicializaActores import inicializaActoresPorNombre
from accion_terminarHistoriaNormal import terminarHistoriaNormal
from accion_terminarHistoriaNoHayAmor import terminarHistoriaNoHayAmor

acciones = [inicializaActoresPorNombre, terminarHistoriaNormal, terminarHistoriaNoHayAmor]