from submeta_ejecutarSecuestro import ejecutarSecuestro
from submeta_obtenerInformacionSecuestro import obtenerInformacionSecuestro
from submeta_ejecutarPlanSalvar import ejecutarPlanSalvar

submetas = [ejecutarSecuestro, obtenerInformacionSecuestro, ejecutarPlanSalvar]